name: Daily News Crawler

on:
  schedule:
    # 每天晚上 8:30 运行
    - cron: '30 12 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # 选择 Python 版本

      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 运行爬虫脚本
      - name: Run News Crawler
        run: |
          python fench.py

      # 推送更新到仓库
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update news files for $(date +'%Y-%m-%d')"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
